automation:
- alias: Office - Automatic Lights
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.office_motion_sensors
    from: 'off'
    to: 'on'
    id: MotionOn
    trigger: state
  - entity_id:
    - binary_sensor.office_motion_sensors
    from: 'on'
    to: 'off'
    id: MotionOff
    for:
      hours: 0
      minutes: 0
      seconds: 0
    trigger: state
  - trigger: state
    entity_id:
    - light.office_group_all_lights
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 10
      seconds: 0
    id: Trigger_LightSource_Off
  - entity_id:
    - binary_sensor.office_motion_sensors
    from: 'on'
    to: 'off'
    id: MotionIdle
    for:
      hours: 0
      minutes: 0
      seconds: 15
    trigger: state
    enabled: false
  - entity_id:
    - sensor.apollo_mtr_1_ce9998_hallway_target_1_angle
    id: Hallway Angle
    below: -30
    enabled: false
    trigger: numeric_state
  - entity_id:
    - light.aqara_t1m_ceiling_main_light
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: Light ON 30
    enabled: false
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - MotionOn
      sequence:
      - if:
        - condition: template
          value_template: '{{ is_state(''input_boolean.adaptive_lighting_reset_office'',
            ''off'') }}

            '
          alias: Input Boolean Adaptive Lighting Reset == Off
        then:
        - action: scene.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
              | lower | replace(" ", "_") }}

              '
          alias: Activate current scene in Scene Selector
        else:
        - action: input_select.select_option
          metadata: {}
          data:
            option: Adaptive Lighting Reset
          target:
            entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

              '
          alias: Scene Selector SELECT Adaptive Lighting Reset
        - action: input_boolean.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: input_boolean.adaptive_lighting_reset_{{area_name}}
          alias: Input boolean  TURN OFF Adaptive Lighting Reset
    - conditions:
      - condition: trigger
        id:
        - MotionOff
      sequence:
      - action: scene.create
        metadata: {}
        data:
          scene_id: '{{device_id}}_{{button_name}}_last_on

            '
          snapshot_entities: '{{ expand(light_source) | map(attribute=''entity_id'')
            | list }}

            '
      - action: input_select.select_option
        metadata: {}
        data:
          option: Last On
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
        alias: Scene Selector SELECT Last On
      - target:
          entity_id: '{{light_source}}

            '
        data:
          transition: 30
        action: light.turn_off
        alias: Light TURN OFF light_source
    - conditions:
      - condition: trigger
        id:
        - MotionIdle
      sequence:
      - metadata: {}
        data:
          brightness_step_pct: -50
        target:
          entity_id: light.aqara_t1m_ceiling_main_light
        enabled: false
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - Trigger_LightSource_Off
      sequence:
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.adaptive_lighting_reset_{{area_name}}
        alias: Input Boolean TURN ON Adaptive Lighting Reset
    - conditions:
      - condition: trigger
        id:
        - Hallway Angle
      - condition: state
        entity_id: light.aqara_t1m_ceiling_main_light
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.apollo_mtr_1_ce9998_hallway_target_1_x
        above: 20
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id:
          - light.aqara_t1m_ceiling_main_light
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - Light ON 30
      - condition: state
        entity_id: binary_sensor.office_motion_sensors
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.everything_presence_lite_f1c3b8_target_1_angle
        below: 30
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.aqara_t1m_ceiling_main_light
        action: light.turn_off
  variables:
    room: office
    device_id: d966bfe5eaa4645f72ff45022220e12d
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    light_source: light.office_group_all_lights
    area_name: '{{area_name(trigger.entity_id)}}'
  mode: single
  '#id': '1714185396253'
  enabled: false
