automation:
- alias: Office - Scene Controller - Button 5 - Press
  description: ''
  triggers:
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed
    id: Trigger_Press_1x
    trigger: event
    alias: Press 1x
  - alias: Press 2x
    event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed2x
    id: Trigger_Press_2x
    trigger: event
  - alias: Press 3x
    event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed3x
    id: Trigger_Press_3x
    trigger: event
  - alias: Press 4x
    event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed4x
    id: Trigger_Press_4x
    trigger: event
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyPressed5x
    id: Trigger_Press_5x
    trigger: event
    alias: Press 5x
    enabled: false
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyHeldDown
    id: Trigger_Press_Hold
    trigger: event
    alias: Press Hold
  - event_type: zwave_js_value_notification
    event_data:
      device_id: '{{device_id}}

        '
      property_key: '{{property_key}}

        '
      value: KeyReleased
    id: Trigger_Press_Release
    trigger: event
    alias: Press Release
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_1x
      - condition: template
        value_template: '{{ is_state(light_source, ''on'') }}'
      sequence:
      - action: scene.create
        metadata: {}
        data:
          scene_id: '{{device_id}}_{{button_name}}_last_on

            '
          snapshot_entities: '{{ expand(light_source) | map(attribute=''entity_id'')
            | list }}

            '
      - action: input_select.select_first
        metadata: {}
        data: {}
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
      - target:
          entity_id: '{{light_source}}

            '
        data: {}
        action: light.turn_off
      alias: Press 1X - 1 - Turn Off
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_1x
      - condition: template
        value_template: '{{ is_state(light_source, ''off'') }}'
      sequence:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
            | lower | replace(" ", "_") }}

            '
      alias: Press 1X - 2 - Turn On
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_2x
      sequence:
      - action: input_select.select_next
        metadata: {}
        data:
          cycle: true
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
      alias: Press 2X
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_3x
      sequence:
      - action: input_select.select_last
        metadata: {}
        data: {}
        target:
          entity_id: input_select.d966bfe5eaa4645f72ff45022220e12d_button_5_scene_input
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: 'scene.{{device_id}}_{{button_name}}_default

            '
        enabled: false
      - action: adaptive_lighting.apply
        metadata: {}
        data:
          entity_id: 'switch.adaptive_lighting_{{area_name}}

            '
        enabled: false
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
            | lower | replace(" ", "_") }}

            '
      alias: Press 3X
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_4x
      sequence:
      - action: input_boolean.toggle
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.adaptive_lighting_prefer_rgb_color_{{area_name}}
      - action: persistent_notification.create
        metadata: {}
        data:
          title: zwave area
          message: 'Device {{ trigger.event.data.device_id }} is in area ID: {{area_name
            }}'
        enabled: false
      alias: Press 4X
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_5x
      sequence: []
      alias: Press 5X - 1 - State ON
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_Hold
      sequence:
      - action: automation.toggle
        target:
          entity_id: 'automation.{{area_name}}_motion_sensor

            '
        data: {}
      alias: Press Hold - Automatic Lights Toggle
    - conditions:
      - condition: trigger
        id:
        - Trigger_Press_Release
      sequence:
      - if:
        - condition: state
          entity_id: light.office_group_all_lights
          state: 'off'
        then:
        - action: switch.turn_off
          target:
            entity_id:
            - switch.zen32_scene_controller_d966bfe5eaa4645f72ff45022220e12d_button_1_indication_binary
          data: {}
        enabled: false
      alias: Press Hold - 2 - Release
    enabled: true
  trigger_variables:
    device_id: d966bfe5eaa4645f72ff45022220e12d
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    property_key: '{{ ''00'' ~ button_number }}'
    light_source: light.office_group_all_lights
  variables:
    room: office
    area_name: '{{ area_name(trigger.event.data.device_id) | lower | replace('' '',
      ''_'') }}'
  mode: single
  '#id': '1712427798099'
  enabled: false
- alias: Office - Scene Controller - Button 5 - LED Indicator
  description: Toggles LED and changes colors based on Entity statuses
  triggers:
  - entity_id:
    - light.office_group_all_lights
    to: 'on'
    from: 'off'
    id: Button_Source_On
    trigger: state
    enabled: true
  - entity_id:
    - light.office_group_all_lights
    to: 'off'
    from: 'on'
    id: Button_Source_Off
    trigger: state
    enabled: true
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - entity_id:
    - automation.office_motion_sensor
    from: 'off'
    to: 'on'
    id: AutomaticLights_On
    trigger: state
    enabled: true
  - entity_id:
    - automation.office_motion_sensor
    from: 'on'
    to: 'off'
    id: AutomaticLights_Off
    trigger: state
    enabled: true
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Button_Source_On
      sequence:
      - data: {}
        action: switch.turn_on
        target:
          entity_id: '{{led_switch_name}}

            '
    - conditions:
      - condition: trigger
        id:
        - Button_Source_Off
      sequence:
      - action: switch.turn_off
        target:
          entity_id: '{{led_switch_name}}

            '
        data: {}
    - conditions:
      - condition: trigger
        id:
        - AutomaticLights_On
      sequence:
      - target:
          device_id: '{{device_id}}

            '
        data:
          parameter: '6'
          value: Green
          device_id: '{{device_id}}

            '
        action: zwave_js.set_config_parameter
    - conditions:
      - condition: trigger
        id:
        - AutomaticLights_Off
      sequence:
      - target:
          device_id: '{{device_id}}

            '
        data:
          parameter: '6'
          value: Red
          device_id: '{{device_id}}

            '
        action: zwave_js.set_config_parameter
    enabled: true
  variables:
    device_id: d966bfe5eaa4645f72ff45022220e12d
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    led_number: '{{ (button_number | int % 5) + 1 }}'
    led_switch_name: '{{ ''switch.zen32_scene_controller_'' ~device_id~ ''_button_''
      ~led_number~ ''_indication_binary'' }}'
  mode: single
  '#id': '1726289967466'
  enabled: false
- alias: Office - Scene Controller - Button 5 - Activate Scene
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_select.d966bfe5eaa4645f72ff45022220e12d_button_5_scene_input
    id: Trigger_SceneInput
    enabled: true
  - trigger: state
    entity_id:
    - scene.d966bfe5eaa4645f72ff45022220e12d_button_5_adaptive_lighting_reset
    to: null
    id: Trigger_AdaptiveLightingReset
    enabled: false
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
        | lower | replace(" ", "_") }}

        '
    enabled: false
  - if:
    - condition: template
      value_template: '{{ states(''input_select.'' + device_id + ''_button_5_scene_input'')
        == ''Adaptive Lighting Reset'' }}

        '
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
          | lower | replace(" ", "_") }}

          '
      enabled: true
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - action: adaptive_lighting.apply
      metadata: {}
      data:
        entity_id: switch.adaptive_lighting_{{area_name}}
    else:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
          | lower | replace(" ", "_") }}

          '
      enabled: true
  variables:
    device_id: d966bfe5eaa4645f72ff45022220e12d
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    area_name: '{{area_name(trigger.entity_id)}}'
  mode: single
  '#id': '1757727092691'
  enabled: false
- alias: Office - Automatic Lights
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.office_motion_sensors
    from: 'off'
    to: 'on'
    id: MotionOn
    trigger: state
  - entity_id:
    - binary_sensor.office_motion_sensors
    from: 'on'
    to: 'off'
    id: MotionOff
    for:
      hours: 0
      minutes: 0
      seconds: 0
    trigger: state
  - trigger: state
    entity_id:
    - light.office_group_all_lights
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
    id: Trigger_LightSource_Off
  - entity_id:
    - binary_sensor.office_motion_sensors
    from: 'on'
    to: 'off'
    id: MotionIdle
    for:
      hours: 0
      minutes: 0
      seconds: 15
    trigger: state
    enabled: false
  - entity_id:
    - sensor.apollo_mtr_1_ce9998_hallway_target_1_angle
    id: Hallway Angle
    below: -30
    enabled: false
    trigger: numeric_state
  - entity_id:
    - light.aqara_t1m_ceiling_main_light
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 30
    id: Light ON 30
    enabled: false
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - MotionOn
      sequence:
      - if:
        - condition: state
          entity_id: input_boolean.adaptive_lighting_reset_office
          state: 'off'
        then:
        - action: scene.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: 'scene.{{device_id}}_{{button_name}}_{{ states(''input_select.''~device_id~''_''~button_name~''_scene_input'')
              | lower | replace(" ", "_") }}

              '
        else:
        - action: scene.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: 'scene.{{device_id}}_{{button_name}}_adaptive_lighting_reset

              '
          enabled: false
        - action: input_select.select_last
          metadata: {}
          data: {}
          target:
            entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

              '
        - action: input_boolean.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: input_boolean.adaptive_lighting_reset_{{area_name}}
    - conditions:
      - condition: trigger
        id:
        - MotionOff
      sequence:
      - action: scene.create
        metadata: {}
        data:
          scene_id: '{{device_id}}_{{button_name}}_last_on

            '
          snapshot_entities: '{{ expand(light_source) | map(attribute=''entity_id'')
            | list }}

            '
      - action: input_select.select_first
        metadata: {}
        data: {}
        target:
          entity_id: 'input_select.{{device_id}}_{{button_name}}_scene_input

            '
      - target:
          entity_id: '{{light_source}}

            '
        data:
          transition: 30
        action: light.turn_off
    - conditions:
      - condition: trigger
        id:
        - MotionIdle
      sequence:
      - metadata: {}
        data:
          brightness_step_pct: -50
        target:
          entity_id: light.aqara_t1m_ceiling_main_light
        enabled: false
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - Trigger_LightSource_Off
      sequence:
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.adaptive_lighting_reset_{{area_name}}
    - conditions:
      - condition: trigger
        id:
        - Hallway Angle
      - condition: state
        entity_id: light.aqara_t1m_ceiling_main_light
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.apollo_mtr_1_ce9998_hallway_target_1_x
        above: 20
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id:
          - light.aqara_t1m_ceiling_main_light
        action: light.turn_on
    - conditions:
      - condition: trigger
        id:
        - Light ON 30
      - condition: state
        entity_id: binary_sensor.office_motion_sensors
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.everything_presence_lite_f1c3b8_target_1_angle
        below: 30
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: light.aqara_t1m_ceiling_main_light
        action: light.turn_off
  variables:
    room: office
    device_id: d966bfe5eaa4645f72ff45022220e12d
    button_name: button_5
    button_number: '{{ button_name.split(''_'')[1] }}'
    light_source: light.office_group_all_lights
    area_name: '{{area_name(trigger.entity_id)}}'
  mode: single
  '#id': '1714185396253'
  enabled: false
